version: 2.1

jobs:
  test-image-arm:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: test
          command: |
            docker run -it --rm -v .:/app -w /app cypress/included
          working_directory: examples/basic-mini
  test-image-amd:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: test
          command: |
            docker run -it --rm -v .:/app -w /app cypress/included
          working_directory: examples/basic-mini

workflows:
  test:
    jobs:
        - test-image-arm
        - test-image-amd
