version: 2.1

jobs:
  test-image:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm ci
          working_directory: examples/chromium
      - run:
          name: test
          command: |
            docker compose run --rm --build test-cypress-chromium
          working_directory: examples/chromium

workflows:
  test:
    jobs:
        - test-image
